# This workflow will build a docker image and push it to dockerhub docker registry
# For more information see: https://github.com/marketplace/actions/build-and-push-docker-images

name: Dockerhub Image

on:
  push:
    branches: [ main ]

jobs:
  docker-build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dcaribou/transfermarkt-scraper:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
